<Project>
  <PropertyGroup>
    <MoeTradeMarkerOutputRoot Condition="'$(MoeTradeMarkerOutputRoot)' == ''">$(MSBuildThisFileDirectory)dist/</MoeTradeMarkerOutputRoot>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
