namespace MoeTradeMarker.Shared;

public enum TradeMarkerText
{
    ClientLoaded,
    ClientInitFailed,
    ConfigGeneralSection,
    ConfigDisplaySection,
    ConfigShowTraderMarkerName,
    ConfigShowTraderMarkerDescription,
    ConfigMarkerPositionName,
    ConfigMarkerPositionDescription,
    ConfigMarkerColorName,
    ConfigMarkerColorDescription,
    ConfigLanguageModeName,
    ConfigLanguageModeDescription,
    TooltipTraderMarker,
    ClientItemMarkerMissing,
    ClientMarkerRefreshFailed,
    ClientItemViewTypeMissing,
    ClientSetQuestItemViewPanelMissing,
    ClientItemViewPatchInstalled,
    ClientLanguageSynced,
    ClientLanguageSyncFailed,
    ClientItemReadFailed,
    ClientMainImageReadFailed,
    ClientItemViewComponentReadFailed,
    ServerLoaded,
    ServerConfigLoaded,
    ServerConfigLoadFailed,
    RagfairMarkedItemBlocked,
}
